version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "docker"
    ports:
      - "5432:5432"
    volumes:
      - /home/arthur/Documentos/Workspace/docker/postgres/db:/var/lib/postgresql/data
